title: Diana Rocio Galindo
logo: https://github.com/dianarociogg/dianarociogg.github.io/blob/main/images/logo.png
show_downloads: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
